import sharp from "sharp";
import fs from "fs";
import path from "path";

const inputFolder = "./unc_design";
const outputFolder = "./public/design";
const dataOutputFile = "./src/data/designData.js";

// Recursive function to compress images and maintain folder structure
async function compressFolder(currentInput, currentOutput) {
  if (!fs.existsSync(currentOutput))
    fs.mkdirSync(currentOutput, { recursive: true });

  const entries = fs.readdirSync(currentInput);
  const tasks = [];

  for (const file of entries) {
    const inputPath = path.join(currentInput, file);
    const outputPath = path.join(currentOutput, file);

    const stat = fs.statSync(inputPath);
    if (stat.isDirectory()) {
      tasks.push(compressFolder(inputPath, outputPath));
    } else if (/\.(jpg|jpeg|png|webp|avif)$/i.test(file)) {
      const outputWebp = outputPath.replace(/\.[^/.]+$/, ".webp");

      const task = sharp(inputPath)
        .resize({ width: 1000 })
        .webp({ quality: 80 })
        .toFile(outputWebp)
        .then(() => console.log(`Compressed ${outputWebp}`))
        .catch((err) => console.error(err));

      tasks.push(task);
    }
  }

  await Promise.all(tasks);
}

function generateGalleryData() {
  if (!fs.existsSync(outputFolder)) return;

  const folders = fs.readdirSync(outputFolder).filter((f) => {
    return fs.statSync(path.join(outputFolder, f)).isDirectory();
  });

  const galleryData = folders.map((folder) => {
    const folderPath = path.join(outputFolder, folder);
    const files = fs
      .readdirSync(folderPath)
      .filter((f) => /\.(webp|jpg|jpeg|png)$/i.test(f));

    // Sort files by name in descending order using natural (numeric) sort
    // This correctly handles numbers so "22" comes before "3" rather than regular string sorting.
    const sortedFiles = [...files].sort((a, b) =>
      b.localeCompare(a, undefined, { numeric: true }),
    );

    const title = folder.charAt(0).toUpperCase() + folder.slice(1);

    return {
      id: folder,
      title: title,
      description: `Collection of ${title} photos`,
      coverImage:
        sortedFiles.length > 0 ? `/gallery/${folder}/${sortedFiles[0]}` : "",
      images: sortedFiles.map((file) => ({
        url: `/gallery/${folder}/${file}`,
        name: file.replace(/\.[^/.]+$/, ""),
      })),
    };
  });

  const fileContent = `// Auto-generated by scripts/compress.js\nexport const galleryFolders = ${JSON.stringify(galleryData, null, 2)};\n`;
  fs.writeFileSync(dataOutputFile, fileContent);
  console.log(`Generated ${dataOutputFile}`);
}

async function run() {
  console.log("Starting compression...");
  await compressFolder(inputFolder, outputFolder);
  console.log("Generating metadata...");
  generateGalleryData();
  console.log("Done!");
}

run();
